<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Item::query()->insert($this->format([
            '4/6-pack yokes',
            '4/6-pack yokes (Ospar-1)',
            'Aluminium Foil',
            'Animal (dead)',
            'Ashtray',
            'Auto (Body Part)',
            'Auto (Fanbelt)',
            'Auto (Hubcap)',
            'Auto (Motor Oil Container)',
            'Auto (Oil Filter)',
            'Auto (Tie Down Strap)',
            'Auto (Tire)',
            'Auto (Tire Tread)',
            'Auto (Wiperblade)',
            'Auto (Wiper Fluid Container)',
            'Bag',
            'Bag (Ospar-60)',
            'Bag (Fast Food)',
            'Bag (for Poo)',
            'Bag (small, e.g. freezer bags)',
            'Bag (small, e.g. freezer bags) (Ospar-3)',
            'Bag (of Litter)',
            'Bag (Reusable)',
            'Bag (Shopping)',
            'Bag (Shopping) (Ospar-2)',
            'Bag (with Poo)',
            'Bag Ends',
            'Bag Ends (Ospar-112)',
            'Ball',
            'Balloon',
            'Balloon with ribbon',
            'Balloon, plastic valve, ribbons etc (Ospar-49)',
            'Bar (Energy Bar)',
            'Battery',
            'Bicycle',
            'Bicyclelock',
            'Bin',
            'Bin (Adopted)',
            'Bin (Exploded)',
            'Bin (Overflowing)',
            'Bone',
            'Bonuscard',
            'Book',
            'Boot',
            'Boot (Ospar-50)',
            'Bottle',
            'Bottle (Alcohol)',
            'Bottle (Beer)',
            'Bottle (Cleaner)',
            'Bottle (Cleaner) (Ospar-5)',
            'Bottle (Energy Drink)',
            'Bottle (Icetea)',
            'Bottle (Juice)',
            'Bottle (Milk)',
            'Bottle (Oil < 50cm)',
            'Bottle (Oil < 50cm) (Ospar-8)',
            'Bottle (Oil > 50cm)',
            'Bottle (Oil > 50cm) (Ospar-9)',
            'Bottle (Protein Drink)',
            'Bottle (Shampoo)',
            'Bottle (Shampoo) (Ospar-7)',
            'Bottle (Shower Gel)',
            'Bottle (Shower Gel) (Ospar-7)',
            'Bottle (Sirop)',
            'Bottle (Soda)',
            'Bottle (Spirit)',
            'Bottle (Sportsdrink)',
            'Bottle (Sun Lotion)',
            'Bottle (Sun Lotion) (Ospar-7)',
            'Bottle (Thermos)',
            'Bottle (Water)',
            'Bottle (Wine)',
            'Bottlecap',
            'Bowl',
            'Box',
            'Box (Cigars)',
            'Box (Matches)',
            'Box (Pizza)',
            'Bra',
            'Bread',
            'Brush',
            'Brush (Ospar-18)',
            'Brush (Paint)',
            'Brush (Paint) (Ospar-73)',
            'Bucket',
            'Bucket (Ospar-38)', 
            'Building Insulation',
            'Bullet',
            'Bullet (Casing)',
            'Float/Buoy',
            'Float/Buoy (Ospar-37)',
            'Cable Tie/Tie Wrap',
            'Can',
            'Can (Aerosol)',
            'Can (Alcohol)',
            'Can (Beer)',
            'Can (Coffee)',
            'Can (Dairy)',                                
            'Can (Deposit: No)',
            'Can (Deposit: Yes)',
            'Can (Energy Drink)',
            'Can (Ice Tea)',
            'Can (Juice)',
            'Can (Milk)',
            'Can (Soda)',
            'Can (state: crushed, deposit: No)',
            'Can (state: crushed, deposit: Yes)',
            'Can (state: dented, deposit: No)',
            'Can (state: dented, deposit: Yes)',
            'Can (state: intact, deposit: No)',
            'Can (state: intact, deposit: Yes)',
            'Can (state: shattered, deposit: No)',
            'Can (state: shattered, deposit: Yes)',
            'Can (Water)',
            'Can (Wine)',
            'Cap (Joint Tube Cap)',
            'Cap (Nitrous Canister Cap)',
            'Cassette Tape',
            'Cd',
            'Cigar Butt',
            'Cigarette Butt',
            'Cigarette Butt (Ospar-64)',
            'Cigarette Filter',
            'Clothes Hanger',
            'Clothes pin',
            'Clothing',
            'Clothing (Ospar-54)',
            'Coaster',
            'Coffeepad',
            'Comb',
            'Comb (Ospar-18)',
            'Condom',
            'Confetti',
            'Confetti Cannon',
            'Container',
            'Container (Antifreeze)',
            'Container (Cleaning Supplies)',
            'Container (Medication)',
            'Cooling Element',
            'Cork',
            'Cork (Ospar-68)',
            'Covid Selftest',
            'Crab/lobster pots (Plastic-26)',
            'Crab/lobster pots (Wood, Ospar-71)',
            'Crate',
            'Crate (Plastic, Ospar-13)',
            'Crate (Wood, Ospar-70)',
            'Creamer Cup',
            'Cup',
            'Cup (Paper, Oscar-65)',
            'Cup (Plastic, Oscar-21)',
            'Cup (Beer)',
            'Cup (Coffee)',
            'Cup (Dairy)',
            'Cup (Ice)',
            'Cup (Lid still attached)',
            'Cup (Milk)',
            'Cup (Milkshake)',
            'Cup (Soda)',
            'Cup (Yoghurt)',
            'Cutlery',
            'Cutlery (Chips fork) (Wood, Ospar-72)',
            'Cutlery (Ospar-22)',
            'Cutlery (Fork)',
            'Cutlery (Knife)',
            'Cutlery (Spoon)',
            'Cutlery (Spork)',
            'De-Icer',
            'Deodorant',
            'Deodorant (Ospar-7)',
            'DepositInBin',
            'Diaper',
            'Dog Tag',
            'Drink Carton',
            'Drink Carton (Ospar-62)',
            'Drink Carton (Icetea)',
            'Drink Carton (Juice)',
            'Drink Carton (Milk)',
            'Drink Carton (Milk) (Ospar-118)',
            'Drink Carton (Water)',
            'Drink Carton (Wine)',
            'Drink Pouch',
            'Drone',
            'Drug Test',
            'Drug Test (DrugWipe)',
            'Duck Decoy',
            'Ear Plug',
            'Ear Swab',
            'Elastic Band',
            'Electric Wire',
            'Event Bracelet',
            'Facemask',
            'Fertiliser/animal feed bags (Ospar-23)',
            'Fireworks',
            'Fireworks (Knetterbal)',
            'Fish boxes',
            'Fish boxes (Plastic, Ospar-34)',
            'Fish boxes (Wood, Ospar-119)',
            'Fishing Line (angling)',
            'Fishing Line (angling) (Ospar-35)',
            'Flyer',
            'Food',
            'Fruit',
            'Fruit (Apple)',
            'Fruit (Banana)',
            'Furnishing',
            'Furnishing (Ospar-55)',
            'Gas Tank',
            'Gel',
            'Gel (Carbo Gel)',
            'Gel (Energy Gel)',
            'Glass',
            'Glasses',
            'Glove',
            'Glove (typical washing up gloves)',
            'Glove (typical washing up gloves) (Ospar-25)',
            'Glove (industrial/professional gloves)'
            'Glove (industrial/professional gloves) (Ospar-113)'
            'Glove',
            'Golf Ball',
            'Gum',
            'Hair Tie',
            'Hand Sanitizer',
            'Hard Hat',
            'Hard Hat (Ospar-42)',
            'Hub Cap',
            'Inhaler',
            'Injection Gun Container',
            'Injection Gun Container (Ospar-11)',
            'Jar',
            'Jerry Can',
            'Jerry Can (Ospar-10)',
            'Joint',
            'Joint Tube',
            'Key',
            'Key Chain',
            'Knife',
            'label',
            'Label (for Bottle)',
            'Light stick',
            'Light stick (Ospar-36)',                                            
            'Lobster and fish tags (Ospar-114)',
            'Lego',
            'Lid',
            'Lid (Coffee Cup)',
            'Lid (Cup)',
            'Lid (Dairy Cup)',
            'Lid (Ice Cup)',
            'Lid (Jar)',
            'Lid (Milk Cup)',
            'Lid (Sauce Packet)',
            'Lid (Straw still attached)',
            'Lid (Yoghurt Cup)',
            'Light',
            'Light (Bicycle)',
            'Lighter',
            'Lighter (Ospar-16)',
            'Lollipop',
            'Mash Vegetable Bags (Ospar-24)',
            'Mirror',
            'Mirror (broken)',
            'Money',
            'Nail',
            'Nail File',
            'Napkin',
            'Net',
            'Net and pieces of net (less than 50 cm)',
            'Net and pieces of net (less than 50 cm) (Ospar-115)',
            'Net and pieces of net (more than 50 cm)',
            'Net and pieces of net (more than 50 cm) (Ospar-116)',
            'Net (Birdfood)',
            'Net (Fishing)',
            'Newspaper or magazine',
            'Newspaper or magazine (Ospar-66)',
            'Nicopods',
            'Nitrous Canister',
            'Numberplate',
            'Nurdle',
            'Octopus Pot (Ospar-27)',
            'OTHER (For something that is not in the picklist)',
            'Oyster net or mussel bag including plastic stopper (Ospar-28)'
            'Oyster trays (round from oyster cultures) (Ospar-29)',
            'Sheeting from mussel culture (Tahitians) (Ospar-30)',
            'Pacifier/Soother',
            'Pack (Cigarette)',
            'Pack (Cigarette) (Ospar-63)',
            'Packaging',
            'Packaging (Balloon)',
            'Packaging (Bubblewrap)',
            'Packaging (Candy Wrapper)',
            'Packaging (Cans)',
            'Packaging (Chips Bag)',
            'Packaging (Cigarette Box Wrapper)',
            'Packaging (Clam Shell)',
            'Packaging (Condom)',
            'Packaging (Facemasks)',
            'Packaging (Folded Drugs Wrapper)',
            'Packaging (Gum Container)',
            'Packaging (Gum Strip)',
            'Packaging (Lollipop Wrapper)',
            'Packaging (Medicine Strip)',
            'Packaging (Nicopods)',
            'Packaging (Nitrous Canister)',
            'Packaging (Rolling papers)',
            'Packaging (Straw)',
            'Packaging (Straw, Straw still inside)',
            'Packaging (Styrofoam)',
            'Packaging (Tissue)',
            'Packaging (Vape Pen)',
            'Pallet (Ospar-69)',
            'Part of something',
            'Part of something (Bicycle)',
            'Part of something (Car)',
            'Part of something (Motor)',
            'Part of something (Phone)',
            'Part of something (Vape Pen)',
            'Pellet (Airsoft)',
            'Pen',
            'Pen (Ospar-17)',
            'Pen (Ballpoint)',
            'Pen (Marker)',
            'Pencap',
            'Pencil',
            'Phone',
            'Phoneholder',
            'Plate',
            'Polluted Area',
            'Poo',
            'Poo (Cat)',
            'Poo (Dog)',
            'Poster',
            'Pot',
            'Propane Tank',
            'Propane Tank (1lbs)',
            'Propane Tank (20lbs)',
            'Pull Ring',
            'Receipt',
            'Reflector',
            'Ribbon',
            'Rolling Papers',
            'Rope/string/cord (diameter < 1cm)',
            'Rope/string/cord (diameter < 1cm) (Ospar-32)',
            'Rope/string/cord (diameter > 1cm)',
            'Rope/string/cord (diameter > 1cm) (Ospar-31)',
            'Sachet',
            'Sachet (Creamer)',
            'Sachet (Ketchup)',
            'Sachet (Mayonaise)',
            'Sachet (Mustard)',
            'Sachet (Salt)',
            'Sachet (Sugar)',
            'Sacking',
            'Sacking (Ospar-56)',
            'Sandpaper',
            'Saucepacket',
            'Screw',
            'Shoe',
            'Shoes/Sandals (Leather, Ospar-57)',
            'Shoes/Sandals (Plastic, Ospar-44)',
            'Shopping Cart',
            'Shotglass',
            'Shotgun Cartridge',
            'Shotgun Cartridge (Ospar-43)',
            'Sigar',
            'Sleeve (for Bottle)',
            'Snus',
            'Sock',
            'Sponge',
            'Sponge (Foam Sponge) Ospar-45)',
            'Spray Can',
            'Spray Can (Cockpitspray)',
            'Spray Can (Paint)',
            'Stick',
            'Stick (Icelolly)',
            'Stick (Lolly)',
            'Stick (Lolly) (Plastic, Ospar-19)',
            'Stick (Lolly) (Wood, Ospar-72)',
            'Sticker',
            'Stirrer',
            'Strapping band',
            'Strapping band (Ospar-39)',
            'Straw',
            'Straw (Ospar-22)',
            'Styrofoam',
            'Syringe',
            'Tampon',
            'Tangled nets/cord/rope and string',
            'Tangled nets/cord/rope and string (Ospar-33)',
            'Tape',
            'Tape (Caution)',
            'Tape (Duct Tape),
            'Tape (Electrical)',
            'Tape (Flagging)',
            'Teabag',
            'Ticket',
            'Ticket (Bus)',
            'Ticket (Parking)',
            'Ticket (Train)',
            'Tile',
            'Tire',
            'Tissue',
            'Tobacco Pouch',
            'Token',
            'Toothbrush',
            'Toothpaste',
            'Toothpick',
            'Toy',
            'Toy & Party Poppers (Ospar-20)',
            'Toy (Nerf Bullet)',
            'Toy (Waterpistol)',
            'Tray',
            'Tray (Ospar-22)',
            'Tyre',
            'Tyre and belts (Ospar-52)',
            'Umbrella',
            'Unidentified/Unknown',
            'Vape Oil',
            'Vape Pen',
            'Wallet',
            'Wet Wipes',
            'Wrapper',
            'Zip Bag',
        ]));
    }

    private function format(array $items): array
    {
        return array_map(fn (string $item) => [
            'name' => $item,
            'slug' => Str::slug($item),
            'created_at' => now(),
            'updated_at' => now(),
        ], $items);
    }
}
