<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Item::query()->insert($this->format([
            'Aluminium Foil',
            'Animal (dead)',
            'Ashtray',
            'Auto (Body Part)',
            'Auto (Fanbelt)',
            'Auto (Hubcap)',
            'Auto (Motor Oil Container)',
            'Auto (Oil Filter)',
            'Auto (Tie Down Strap)',
            'Auto (Tire)',
            'Auto (Tire Tread)',
            'Auto (Wiperblade)',
            'Auto (Wiper Fluid Container)',
            'Bag',
            'Bag (Fast Food)',
            'Bag (for Poo)',
            'Bag (Grocery)',
            'Bag (of Litter)',
            'Bag (Reusable)',
            'Bag (with Poo)',
            'Ball',
            'Balloon',
            'Bar (Energy Bar)',
            'Battery',
            'Bicycle',
            'Bicyclelock',
            'Bin',
            'Bin (Adopted)',
            'Bin (Exploded)',
            'Bin (Overflowing)',
            'Bone',
            'Bonuscard',
            'Book',
            'Bottle',
            'Bottle (Alcohol)',
            'Bottle (Beer)',
            'Bottle (Energy Drink)',
            'Bottle (Icetea)',
            'Bottle (Juice)',
            'Bottle (Milk)',
            'Bottle (Oil)',
            'Bottle (Protein Drink)',
            'Bottle (Sirop)',
            'Bottle (Soda)',
            'Bottle (Spirit)',
            'Bottle (Sportsdrink)',
            'Bottle (Sunscreen)',
            'Bottle (Thermos)',
            'Bottle (Water)',
            'Bottle (Wine)',
            'Bottlecap',
            'Bowl',
            'Box',
            'Box (Cigarette)',
            'Box (Cigars)',
            'Box (Matches)',
            'Box (Pizza)',
            'Bra',
            'Bread',
            'Bullet (Casing)',
            'Buoy',
            'Butt (Cigar)',
            'Butt (Cigarette)',
            'Cable Tie',
            'Can',
            'Can (Aerosol)',
            'Can (Alcohol)',
            'Can (Beer)',
            'Can (Coffee)',
            'Can (Dairy)',
            'Can (Deposit: No)',
            'Can (Deposit: Yes)',
            'Can (Energy Drink)',
            'Can (Ice Tea)',
            'Can (Juice)',
            'Can (Milk)',
            'Can (Soda)',
            'Can (state: crushed, deposit: No)',
            'Can (state: crushed, deposit: Yes)',
            'Can (state: dented, deposit: No)',
            'Can (state: dented, deposit: Yes)',
            'Can (state: intact, deposit: No)',
            'Can (state: intact, deposit: Yes)',
            'Can (state: shattered, deposit: No)',
            'Can (state: shattered, deposit: Yes)',
            'Can (Water)',
            'Can (Wine)',
            'Cap (Bottle)',
            'Cap (Joint Tube)',
            'Cap (Nitrous Canister)',
            'Cassette Tape',
            'Cd',
            'Cigarette Butt',
            'Cigarette Filter',
            'Clothes Hanger',
            'Clothespin',
            'Clothing',
            'Coaster',
            'Coffeepad',
            'Comb',
            'Condom',
            'Confetti',
            'Confetti Cannon',
            'Container (Antifreeze)',
            'Container (Cleaning Supplies)',
            'Container (Medication)',
            'Cooling Element',
            'Cork',
            'Covid Selftest',
            'Creamer Cup',
            'Cup',
            'Cup (Beer)',
            'Cup (Coffee)',
            'Cup (Dairy)',
            'Cup (Ice)',
            'Cup (Lid still attached)',
            'Cup (Milk)',
            'Cup (Milkshake)',
            'Cup (Soda)',
            'Cup (Yoghurt)',
            'Cutlery',
            'De-Icer',
            'Deodorant',
            'Diaper',
            'Dog Tag',
            'Drink Carton',
            'Drink Carton (Icetea)',
            'Drink Carton (Juice)',
            'Drink Carton (Milk)',
            'Drink Carton (Water)',
            'Drink Carton (Wine)',
            'Drink Pouch',
            'Drone',
            'Drug Test (DrugWipe)',
            'Duck Decoy',
            'Ear Plug',
            'Ear Swab',
            'Elastic Band',
            'Electric Wire',
            'Event Bracelet',
            'Facemask',
            'Fireworks',
            'Fireworks (Knetterbal)',
            'Flyer',
            'Food',
            'Fork',
            'Fruit',
            'Fruit (Apple)',
            'Fruit (Banana)',
            'Gas Tank',
            'Gel (Carbo Gel)',
            'Gel (Energy Gel)',
            'Glass',
            'Glasses',
            'Glove',
            'Gum',
            'Hair Tie',
            'Hand Sanitizer',
            'Hub Cap',
            'Inhaler',
            'Jar',
            'jerrycan',
            'Joint',
            'Joint Tube',
            'Key',
            'Key Chain',
            'Knife',
            'label',
            'Label (for Bottle)',
            'Lego',
            'Lid',
            'Lid (Coffee Cup)',
            'Lid (Cup)',
            'Lid (Dairy Cup)',
            'Lid (Ice Cup)',
            'Lid (Jar)',
            'Lid (Milk Cup)',
            'Lid (Sauce Packet)',
            'Lid (Straw still attached)',
            'Lid (Yoghurt Cup)',
            'Light',
            'Light (Bicycle)',
            'Lighter',
            'Lollipop',
            'Mirror',
            'Mirror (broken)',
            'Money',
            'Nail',
            'Nail File',
            'Napkin',
            'Net',
            'Net (Birdfood)',
            'Net (Fishing)',
            'Nicopods',
            'Nitrous Canister',
            'Numberplate',
            'Nurdle',
            'OTHER (For something that is not in the picklist)',
            'Pacifier/Soother',
            'Packaging',
            'Packaging (Balloon)',
            'Packaging (Bubblewrap)',
            'Packaging (Candy Wrapper)',
            'Packaging (Cans)',
            'Packaging (Chips Bag)',
            'Packaging (Cigarette Box Wrapper)',
            'Packaging (Clam Shell)',
            'Packaging (Condom)',
            'Packaging (Facemasks)',
            'Packaging (Folded Drugs Wrapper)',
            'Packaging (Gum Container)',
            'Packaging (Gum Strip)',
            'Packaging (Lollipop Wrapper)',
            'Packaging (Medicine Strip)',
            'Packaging (Nicopods)',
            'Packaging (Nitrous Canister)',
            'Packaging (Rolling papers)',
            'Packaging (Straw)',
            'Packaging (Straw, Straw still inside)',
            'Packaging (Styrofoam)',
            'Packaging (Tissue)',
            'Packaging (Vape Pen)',
            'Part of something',
            'Part of something (Bicycle)',
            'Part of something (Car)',
            'Part of something (Motor)',
            'Part of something (Phone)',
            'Part of something (Vape Pen)',
            'Pellet (Airsoft)',
            'Pen',
            'Pencap',
            'Pencil',
            'Phone',
            'Phoneholder',
            'Plate',
            'Polluted Area',
            'Poo',
            'Poo (Cat)',
            'Poo (Dog)',
            'Poster',
            'Pot',
            'Propane Tank',
            'Propane Tank (1lbs)',
            'Propane Tank (20lbs)',
            'Pull Ring',
            'Receipt',
            'Reflector',
            'Ribbon',
            'Rolling Papers',
            'Rope',
            'Sachet',
            'Sachet (Creamer)',
            'Sachet (Ketchup)',
            'Sachet (Mayonaise)',
            'Sachet (Mustard)',
            'Sachet (Salt)',
            'Sachet (Sugar)',
            'Sandpaper',
            'Saucepacket',
            'Screw',
            'Shoe',
            'Shopping Cart',
            'Shotgun Shell',
            'Sigar',
            'Sleeve (for Bottle)',
            'Snus',
            'Sock',
            'Sponge',
            'Spoon',
            'Spray Can',
            'Spray Can (Cockpitspray)',
            'Spray Can (Paint)',
            'Stick (Icelolly)',
            'Stick (Lollipop)',
            'Sticker',
            'Stirrer',
            'Straw',
            'Straw (Coffee Cup)',
            'Styrofoam',
            'Syringe',
            'Tampon',
            'Tape (Caution)',
            'Tape (Electrical)',
            'Tape (Flagging)',
            'Teabag',
            'Ticket (Bus)',
            'Ticket (Parking)',
            'Ticket (Train)',
            'Tie Wrap',
            'Tile',
            'Tire',
            'Tissue',
            'Tobacco Pouch',
            'Token',
            'Toothbrush',
            'Toothpaste',
            'Toothpick',
            'Toy',
            'Toy (Nerf Bullet)',
            'Toy (Waterpistol)',
            'Tray',
            'Tray (for Cups)',
            'Tyre',
            'Umbrella',
            'Vape Oil',
            'Vape Pen',
            'Wallet',
            'Wet Wipes',
            'Wrapper',
            'Zip Bag',
        ]));
    }

    private function format(array $items): array
    {
        return array_map(fn (string $item) => [
            'name' => $item,
            'slug' => Str::slug($item),
            'created_at' => now(),
            'updated_at' => now(),
        ], $items);
    }
}
