<?php

namespace Database\Seeders;

use App\Models\Item;
use Illuminate\Database\Seeder;

class ItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Item::factory(107)->sequence(
            ['name' => 'Animal (dead)', 'slug' => 'animal(dead)'],
            ['name' => 'Bag', 'slug' => 'bag'],
            ['name' => 'Bag (for Poo)', 'slug' => 'bag(forpoo)'],
            ['name' => 'Bag (of Litter)', 'slug' => 'bag(oflitter)'],
            ['name' => 'Bag with Poo', 'slug' => 'bagwithpoo'],
            ['name' => 'Balloon', 'slug' => 'balloon'],
            ['name' => 'Battery', 'slug' => 'battery'],
            ['name' => 'Bicycle', 'slug' => 'bicycle'],
            ['name' => 'Bicycle Light', 'slug' => 'bicyclelight'],
            ['name' => 'Bicycle Part', 'slug' => 'bicyclepart'],
            ['name' => 'Bin', 'slug' => 'bin'],
            ['name' => 'Bin (Adopted)', 'slug' => 'bin(adopted)'],
            ['name' => 'Bin (Exploded)', 'slug' => 'bin(exploded)'],
            ['name' => 'Bin (Overflowing)', 'slug' => 'bin(overflowing)'],
            ['name' => 'Bottle', 'slug' => 'bottle'],
            ['name' => 'Bottle Cap', 'slug' => 'bottlecap'],
            ['name' => 'Bottle Sleeve', 'slug' => 'bottlesleeve'],
            ['name' => 'Bowl', 'slug' => 'bowl'],
            ['name' => 'Bus Ticket', 'slug' => 'busticket'],
            ['name' => 'Can', 'slug' => 'can'],
            ['name' => 'Car Part', 'slug' => 'carpart'],
            ['name' => 'Cd', 'slug' => 'cd'],
            ['name' => 'Cigarettebutt', 'slug' => 'cigarettebutt'],
            ['name' => 'Cigarettepack', 'slug' => 'cigarettepack'],
            ['name' => 'Clothing', 'slug' => 'clothing'],
            ['name' => 'Cockpitspray', 'slug' => 'cockpitspray'],
            ['name' => 'Coffee Lid', 'slug' => 'coffeelid'],
            ['name' => 'Condom', 'slug' => 'condom'],
            ['name' => 'Cork', 'slug' => 'cork'],
            ['name' => 'Covid Test', 'slug' => 'covidtest'],
            ['name' => 'Creamer Sachet', 'slug' => 'creamersachet'],
            ['name' => 'Cup', 'slug' => 'cup'],
            ['name' => 'Cup Holder', 'slug' => 'cupholder'],
            ['name' => 'Cup Lid', 'slug' => 'cuplid'],
            ['name' => 'Cup Straw', 'slug' => 'cupstraw'],
            ['name' => 'Cutlery', 'slug' => 'cutlery'],
            ['name' => 'Deodorant', 'slug' => 'deodorant'],
            ['name' => 'Diaper', 'slug' => 'diaper'],
            ['name' => 'Drink Carton', 'slug' => 'drinkcarton'],
            ['name' => 'Drink Pouch', 'slug' => 'drinkpouch'],
            ['name' => 'Ear Swab', 'slug' => 'earswab'],
            ['name' => 'Elastic Band', 'slug' => 'elasticband'],
            ['name' => 'Electric Wire', 'slug' => 'electricwire'],
            ['name' => 'Energy Gel', 'slug' => 'energygel'],
            ['name' => 'Fireworks', 'slug' => 'fireworks'],
            ['name' => 'Food', 'slug' => 'food'],
            ['name' => 'Fork', 'slug' => 'fork'],
            ['name' => 'Fruit', 'slug' => 'fruit'],
            ['name' => 'Glass', 'slug' => 'glass'],
            ['name' => 'Glasses', 'slug' => 'glasses'],
            ['name' => 'Glove', 'slug' => 'glove'],
            ['name' => 'Hair Tie', 'slug' => 'hairtie'],
            ['name' => 'Hand Sanitizer', 'slug' => 'handsanitizer'],
            ['name' => 'Hub Cap', 'slug' => 'hubcap'],
            ['name' => 'Icelolly Stick', 'slug' => 'icelollystick'],
            ['name' => 'Joint Tube', 'slug' => 'jointtube'],
            ['name' => 'Key', 'slug' => 'key'],
            ['name' => 'Knife', 'slug' => 'knife'],
            ['name' => 'Lid', 'slug' => 'lid'],
            ['name' => 'Lighter', 'slug' => 'lighter'],
            ['name' => 'Match Box', 'slug' => 'matchbox'],
            ['name' => 'Medicine Strip', 'slug' => 'medicinestrip'],
            ['name' => 'Mustard Sachet', 'slug' => 'mustardsachet'],
            ['name' => 'Nail', 'slug' => 'nail'],
            ['name' => 'Napkin', 'slug' => 'napkin'],
            ['name' => 'Nerfgun Bullet', 'slug' => 'nerfgunbullet'],
            ['name' => 'Net for Birdfood', 'slug' => 'netforbirdfood'],
            ['name' => 'Pacifier', 'slug' => 'pacifier'],
            ['name' => 'Packaging', 'slug' => 'packaging'],
            ['name' => 'Pan', 'slug' => 'pan'],
            ['name' => 'Pen', 'slug' => 'pen'],
            ['name' => 'Pencil', 'slug' => 'pencil'],
            ['name' => 'Phone', 'slug' => 'phone'],
            ['name' => 'Pizza Box', 'slug' => 'pizzabox'],
            ['name' => 'Plate', 'slug' => 'plate'],
            ['name' => 'Poo', 'slug' => 'poo'],
            ['name' => 'Pot', 'slug' => 'pot'],
            ['name' => 'Pull Ring', 'slug' => 'pullring'],
            ['name' => 'Receipt', 'slug' => 'receipt'],
            ['name' => 'Rolling Papers', 'slug' => 'rollingpapers'],
            ['name' => 'Rope', 'slug' => 'rope'],
            ['name' => 'Salt Packet', 'slug' => 'saltpacket'],
            ['name' => 'Sandpaper', 'slug' => 'sandpaper'],
            ['name' => 'Saucepacket', 'slug' => 'saucepacket'],
            ['name' => 'Saucepacket Lid', 'slug' => 'saucepacketlid'],
            ['name' => 'Screw', 'slug' => 'screw'],
            ['name' => 'Spoon', 'slug' => 'spoon'],
            ['name' => 'Spray Can', 'slug' => 'spraycan'],
            ['name' => 'Sticker', 'slug' => 'sticker'],
            ['name' => 'Straw', 'slug' => 'straw'],
            ['name' => 'Styrofoam', 'slug' => 'styrofoam'],
            ['name' => 'Sugar Sachet', 'slug' => 'sugarsachet'],
            ['name' => 'Tie Wrap', 'slug' => 'tiewrap'],
            ['name' => 'Tile', 'slug' => 'tile'],
            ['name' => 'Tobacco Pouch', 'slug' => 'tobaccopouch'],
            ['name' => 'Toothbrush', 'slug' => 'toothbrush'],
            ['name' => 'Toothpaste', 'slug' => 'toothpaste'],
            ['name' => 'Toothpick', 'slug' => 'toothpick'],
            ['name' => 'Toy', 'slug' => 'toy'],
            ['name' => 'Train Ticket', 'slug' => 'trainticket'],
            ['name' => 'Tray', 'slug' => 'tray'],
            ['name' => 'Umbrella', 'slug' => 'umbrella'],
            ['name' => 'Vape Pen', 'slug' => 'vapepen'],
            ['name' => 'Wallet', 'slug' => 'wallet'],
            ['name' => 'Wet Wipes', 'slug' => 'wetwipes'],
            ['name' => 'Zip Bag', 'slug' => 'zipbag'],
            ['name' => '(Other)', 'slug' => '(other)'],
        )->create();
    }
}
