<?php

namespace Database\Seeders;

use App\Models\Tag;
use App\Models\TagType;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class TagSeeder extends Seeder
{
    public function run(): void
    {
        $brand = TagType::query()->create(['name' => 'Brand', 'slug' => 'brand']);
        $material = TagType::query()->create(['name' => 'Material', 'slug' => 'material']);
        $event = TagType::query()->create(['name' => 'Event', 'slug' => 'event']);

        Tag::query()->insert($this->format($this->getEvents(), $event));
        Tag::query()->insert($this->format($this->getBrands(), $brand));
        Tag::query()->insert($this->format($this->getMaterials(), $material));
    }

    private function format(array $tags, Model $type): array
    {
        return array_map(fn (string $tag) => [
            'name' => $tag,
            'slug' => Str::slug($tag),
            'tag_type_id' => $type->id,
            'created_at' => now(),
            'updated_at' => now(),
        ], $tags);
    }

    private function getEvents(): array
    {
        return [
            'BeforeAndAfter',
            'BeforeAndAfter_After',
            'BeforeAndAfter_Before',
            'Canuary',
            'Canuary2024',
            'Cleanup4Sarah',
            'Cleanup4Sarah2024',
            'CornishSplicedTreasureHunt-SpecialFind',
            'CornishSplicedTreasureHunt-item-01',
            'CornishSplicedTreasureHunt-item-02',
            'CornishSplicedTreasureHunt-item-03',
            'CornishSplicedTreasureHunt-item-04',
            'CornishSplicedTreasureHunt-item-05',
            'CornishSplicedTreasureHunt-item-06',
            'CornishSplicedTreasureHunt-item-07',
            'CornishSplicedTreasureHunt-item-08',
            'CornishSplicedTreasureHunt-item-09',
            'CornishSplicedTreasureHunt-item-10',
            'CornishSplicedTreasureHunt-item-bonus',
            'CornishSplicedTreasureHunt2024-01',
            'CornishSplicedTreasureHunt2024-02',
            'CornishSplicedTreasureHunt2024-03',
            'CornishSplicedTreasureHunt2024-04',
            'CornishSplicedTreasureHunt2024-05',
            'CornishSplicedTreasureHunt2024-06',
            'OTHER (For an Event that is not in the picklist)',
            'PeukMeuk',
            'PeukMeuk2024',
            'RedBullLitter',
            'ShowYourImpact',
            'ShowYourImpact_DeAfvalraperBladel',
            'ShowYourImpact_DeGrachtWacht',
            'ShowYourImpact_DeZwerfafvalRuimers',
            'ShowYourImpact_ZaanseZwerfvuilEstafette',
            'ShowYourImpact_ZwerfieRotterdam',
            'WorldCleanupDay',
            'WorldCleanupDay2024',
            'Zaandewandel',
            'Zaandewandel2024',
        ];
    }

    private function getMaterials(): array
    {
        return [
            'Aluminium',
            'Bronze',
            'Ceramic',
            'Copper',
            'Fiberglass',
            'Glass',
            'Iron or Steel',
            'Latex',
            'Metal',
            'OTHER (For a Material that is not in the picklist)',
            'Paper',
            'Plastic',
            'Plastic (ABS)',
            'Plastic (HDPE)',
            'Plastic (LDPE)',
            'Plastic (PC)',
            'Plastic (PE)',
            'Plastic (PEN)',
            'Plastic (PET)',
            'Plastic (PP)',
            'Plastic (PS)',
            'Plastic (PVC)',
            'Plastic (PVDC)',
            'Plexyglass',
            'Styrofoam',
            'Wood',
        ];
    }

    private function getBrands(): array
    {
        return [
            '9',
            '86',
            '555',
            '100% Smoothie',
            '7UP',
            'AaDrink',
            'Abant',
            'Absolut',
            'Acadia',
            'Ace',
            'Actimel',
            'Action',
            'Activa',
            'Active O2',
            'Adnams',
            'Affligem',
            'Aga',
            'AH Vitamin Drink',
            'Airbar',
            'Akhtamar',
            'Alaska',
            'Alesto',
            'Alex Meijer',
            'Alfa',
            'Alfakhr',
            'Almhof',
            'Alpro',
            'Amanie',
            'Amber Leaf',
            'Amicelli',
            'Amigo',
            'Amstel',
            'Amsterdam Brewboys',
            'Anadin',
            'Anchor',
            'Andalooz',
            'Angelos',
            'Anta Flu',
            'Appelsientje',
            'Apple Bandit',
            'Applegreen',
            'Appletiser',
            'Aqua Carpatica',
            'Aqua Twist',
            'Aqua Vale',
            'Aquarius',
            'Arctic Coffee',
            'Argus',
            'Arizona',
            'Arla',
            'Aro',
            'Aromaking',
            'Asado',
            'Asahi',
            'Asda',
            'Atlas',
            'Autodrop',
            'Avoca',
            'Axe',
            'Ayran',
            'Babybel',
            'Bacardi',
            'Backwerk',
            'Baha',
            'Bahlsen',
            'Bakey',
            'Bakkers',
            'Balconi',
            'Balisto',
            'Ballygowan',
            'Bang',
            'Barbican',
            'Bar-le-duc',
            'Barnies Foods',
            'Barr',
            'Barratt',
            'BASF',
            'Basic-fit',
            'Basil Seed',
            'Bastogne',
            'Bavaria',
            'Bazooka',
            'Bear',
            'Bebeto',
            'Becks',
            'Beckys',
            'Beemster',
            'Belin',
            'Belkin',
            'Belvedere',
            'Ben & Jerry's',
            'Ben Shaws',
            'Benecol',
            'Benson & Hedges',
            'Bentasil',
            'Berentzen',
            'Best',
            'Better',
            'Bewleys',
            'Beypazari',
            'Bic',
            'Bifi',
            'Bigga',
            'Biggym',
            'Bio',
            'Biotiful',
            'Bird Brewery',
            'Birra Moretti',
            'Black',
            'Blaes',
            'Blankenheym',
            'blck',
            'Bloonies',
            'Blu',
            'Blueband',
            'BlueBastard',
            'Boba Poke',
            'Bobbys',
            'Bocian',
            'Boels',
            'Boembombali',
            'Bokma',
            'Bolletje',
            'Bols',
            'Bombay',
            'Bongelati',
            'Boost',
            'Boots',
            'Border',
            'Boss',
            'Boston',
            'Bounty',
            'Boursin',
            'Bouwmaat',
            'Bozu',
            'Bp',
            'Brand',
            'Bratee',
            'Bravo',
            'Break',
            'Breaker',
            'Breezer',
            'Brekies',
            'Brewdog',
            'Brinky',
            'Britvic',
            'Bros',
            'Brouwerij t IJ',
            'Brouwers',
            'Btween',
            'Bubbelfrisss',
            'Bubblicious',
            'Bud',
            'Bullit',
            'BumBum',
            'Buonciorno',
            'Burger King',
            'Busta',
            'Butterkist',
            'Buxton',
            'Buys',
            'C&A',
            'Cafe Bonjour',
            'Cafe Nero',
            'Cailler',
            'Calippo',
            'Calve',
            'Calypso',
            'Camaro',
            'Camden Town Brewery',
            'Camel',
            'Campina',
            'Canada Dry',
            'Canderel',
            'Candy Can',
            'Candy King',
            'Candyman',
            'Canei',
            'Cannabis',
            'Capri-Sun',
            'Captainmorgan',
            'Carabao',
            'Carling',
            'Carlsberg',
            'Casal de Ventozela',
            'Casino',
            'Castel Boglione',
            'Celebrations',
            'Chalwa',
            'Chardonnay',
            'Charlies',
            'Chaudfontaine',
            'Cheetos',
            'Chekov',
            'Chenet',
            'Chesterfield',
            'Chio',
            'Chivas Regal',
            'Chocomel',
            'Chocomoment',
            'Chubby',
            'Chupa Chups',
            'Ciftlik',
            'Ciroc',
            'Claro',
            'Clearblue',
            'Clipper',
            'Coca-Cola',
            'Cocio',
            'Coco',
            'Coffeefresh',
            'Coke',
            'Comet',
            'Completa',
            'Compton Orchard',
            'Conimex',
            'Contrex',
            'Coolbest',
            'Cooldrink',
            'Coop',
            'Coopers',
            'Coors',
            'Cornetto',
            'Corona',
            'Cotedor',
            'Courvoisier',
            'Craft Nation',
            'Cricket',
            'Cristal',
            'Cristaline',
            'Croky',
            'Crunch',
            'Crystal',
            'Crystal Clear',
            'Culligan',
            'Cup-a-Soup',
            'Cutters Choice',
            'Daelmans',
            'Daim',
            'Dairylea',
            'Dalga',
            'Dalphin',
            'Damel',
            'Damla',
            'Danio',
            'Danone',
            'Danoontje',
            'Davidoff',
            'De Appelaere',
            'De Kleine Keuken',
            'De Kuyper',
            'De Lekkerste',
            'De Ruijter',
            'De Zaanse Hoeve',
            'Deal',
            'Decathlon',
            'Deen',
            'Dekamarkt',
            'DeKlok',
            'Delmonte',
            'Den Leeuw',
            'Dentalcare',
            'Dentalclinics',
            'Depa',
            'Derby',
            'Desperados',
            'Dewit',
            'Dextro',
            'DeZevenGranen',
            'Dhl',
            'Diamond Mist',
            'Didi',
            'Dimple',
            'Dinnerlady',
            'Dirk',
            'Disco',
            'Djeep',
            'Djoezz',
            'Dock',
            'Dolu',
            'Dominos',
            'Dommelsch',
            'Doom Bar',
            'Dopper',
            'Doritos',
            'Dors',
            'Doublemint',
            'Douwe Egberts',
            'Dove',
            'Download',
            'Dr Foots',
            'Dr Pepper',
            'Dr. Toms',
            'Drakensberg',
            'Drinklicious',
            'Droste',
            'Drum',
            'DrWitt',
            'Dubbeldrank',
            'Dubbelfrisss',
            'Dubbledutch',
            'Dujardin',
            'Dunhill',
            'Dunkin',
            'Duplo',
            'Durex',
            'Duvel',
            'Duyvis',
            'Dvtch',
            'Earth',
            'Eastmans',
            'Eat Natural',
            'Edet',
            'Efes',
            'El Chapo Guzman',
            'El Tequito',
            'Elfbar',
            'ElkeMelk',
            'Elmos',
            'Elpicu',
            'Elux',
            'Embassy',
            'Emerge',
            'Empack',
            'Enkhuizer',
            'Enrgydrnk',
            'Erikli',
            'Eristoff',
            'Esbjaerg',
            'Esso',
            'Estathe',
            'Eti',
            'Etos',
            'Euro Shopper',
            'Eurofresh',
            'Everyday',
            'Evian',
            'Export',
            'Extran',
            'Fa',
            'Fahnenbrau',
            'Family',
            'Fanta',
            'Fastgas',
            'Faxe',
            'Febo',
            'Fentimans',
            'Fernandes',
            'Festini',
            'Fiesta',
            'Fieten Oil',
            'Fin Carre',
            'Fini',
            'Finkbrau',
            'Finley',
            'FireMoon',
            'Firerose',
            'Fireup',
            'First Choice',
            'Fishermans Friend',
            'Fitness Beverwijk',
            'Fizz',
            'Flax',
            'Floralys',
            'Flugel',
            'Foco',
            'Focus',
            'Fortuna',
            'Fortune',
            'Foxx',
            'Franziskaner',
            'Freedent',
            'Freedoms Choice',
            'Freeway',
            'Freez',
            'Freezy',
            'Freshlife',
            'Frezzh',
            'Fria',
            'Frisia',
            'Fristi',
            'Fritt',
            'Frontaal',
            'Frosted',
            'Fruit Shoot',
            'Fruit To Go',
            'Fruitfris',
            'Fruitnfun',
            'Fruittella',
            'Fudo',
            'Fuerza',
            'Fumot',
            'FuzeTea',
            'Gaasbeek',
            'Gall&gall',
            'Gamma',
            'Gardinia',
            'Gato Negro',
            'Gauloises',
            'Gazeuse',
            'Generator',
            'Gerardus',
            'Gerolsteiner',
            'GetMoreVits',
            'Gig',
            'Gio',
            'Gio Coffee',
            'Gladiator',
            'Glentalloch',
            'Gobstopper',
            'Gofast',
            'Gofresh',
            'Gofrik',
            'Gold',
            'Goldenpower',
            'Goldfield',
            'Goldwing',
            'Goose Island',
            'Gordons',
            'Goreme',
            'Grace',
            'Grazzano',
            'Greggs',
            'Grey Goose',
            'Grollz',
            'Grolsch',
            'Guarana',
            'Guinness',
            'Gulpener',
            'Gumus',
            'Gurpinar',
            'GVB',
            'Gwoon',
            'Hamidiye',
            'Hansaplast',
            'Hardthof',
            'Hardwheat',
            'Haribo',
            'Harlekijntjes',
            'Harnas',
            'Havana Club',
            'Hawai',
            'Healthy People',
            'Heets',
            'Heineken',
            'Heinz',
            'Hell',
            'Hema',
            'Hennessy',
            'Henri Willig',
            'Hero',
            'Hertog Jan',
            'Hfc',
            'High5',
            'Highspeed',
            'Highway',
            'Hipro',
            'Hm',
            'Hoegaarden',
            'Hollandia',
            'Holtland',
            'Hoop',
            'Hoppe',
            'Hornbach',
            'Hostess',
            'Hugo',
            'Huls',
            'Hypermalt',
            'Icecappuccino',
            'Icelandic Glacial',
            'Iconix',
            'Idel',
            'IJwit',
            'Ikea',
            'Illy',
            'Indomie',
            'Innocent',
            'Intex',
            'Ipa',
            'Isero',
            'Isostar',
            'Italiano',
            'Ivgbar',
            'Jack Daniels',
            'Jan Vet',
            'Jana',
            'Jarritos',
            'Jawbreaker',
            'Jersey',
            'Jetgum',
            'Jillz',
            'Jim Beam',
            'Jimmys',
            'Jobecker',
            'Johma',
            'John West',
            'Johnnie Walker',
            'Joseph Guy',
            'Jozo',
            'JPS',
            'JRS',
            'Jumbo',
            'Jupiler',
            'Jxp',
            'Ka',
            'Kaapse Draai',
            'Kaars',
            'Kahvealti',
            'Kanjers',
            'Karmi',
            'Kasteel',
            'Kasztelan',
            'Katja',
            'Kaubo',
            'Keizerskroon',
            'Kellyloves',
            'Kent',
            'Kfc',
            'Killa',
            'Kimura Ramune',
            'Kinder',
            'KinderCola',
            'Kiosk',
            'Kirkland',
            'Kitkat',
            'Kizilay',
            'Kleenex',
            'Kleiner Klopfer',
            'Klene',
            'Klusdrop',
            'Knoppers',
            'Knorr',
            'Knuspi',
            'Knvb',
            'Koetjesreep',
            'Kompaan',
            'Kong Strong',
            'Konig Ludwig',
            'Kopiko',
            'Kordaaat',
            'Kordaat',
            'Kornuit',
            'Kozel',
            'Kraax',
            'Krolewskie',
            'Kruidvat',
            'Krupnik',
            'Kwaremont',
            'La Chouffe',
            'La Place',
            'La Versoie',
            'Labello',
            'Lager',
            'Landerbrau',
            'Langenekken',
            'Lark',
            'Lavazza',
            'Lavish',
            'Lays',
            'Lech',
            'Lecoq',
            'Leffe',
            'Lemco',
            'Lemon',
            'Lemony',
            'Licor43',
            'Lidl',
            'Liefmans',
            'Liga',
            'Limancellow',
            'Lindahls',
            'Lindt',
            'Linessa',
            'Lion',
            'Lipton',
            'LM',
            'Locklock',
            'Loise',
            'Lomza',
            'Lonka',
            'LookOLook',
            'Looza',
            'Lost Mary',
            'Lotus',
            'Louise',
            'Loveau',
            'Lovka',
            'Lowlander',
            'Lu',
            'Lucky Strike',
            'Lukoil',
            'Lulu',
            'Lungo',
            'Luxus',
            'M&Ms',
            'Maaza',
            'Maggi',
            'Magnum',
            'Malibu',
            'Maltesers',
            'Maoam',
            'Marie',
            'Markant',
            'Marlboro',
            'Mars',
            'Martini',
            'Marx O Larrys',
            'Mascotte',
            'Mastermate',
            'Mastroianni',
            'Maurten',
            'Maxim',
            'Mazzetto',
            'McDonalds',
            'Megabiz',
            'Megaforce',
            'Meharis',
            'Melangedor',
            'Melkan',
            'Melkunie',
            'Mentos',
            'Merba',
            'Merci',
            'Mexicanos',
            'Mezzomix',
            'Migo',
            'Milbona',
            'Milka',
            'Milky Way',
            'Milner',
            'Milsani',
            'Minkenhus',
            'Minute Maid',
            'Mirinda',
            'Mixxedup',
            'Moersleutel',
            'Mogumogu',
            'Monster',
            'Moods',
            'Mountain Dew',
            'Mr. Cool',
            'Mullermilk',
            'Muszynianka',
            'Mythos',
            'Nakd',
            'Napoleon',
            'Natia',
            'Natural Cool',
            'Naturaqua',
            'Nature Valley',
            'Nescafe',
            'Nestea',
            'New York Pizza',
            'Ngine',
            'Nice',
            'Nigde',
            'Nightwatch',
            'Nikon',
            'Nimm2',
            'Nitro',
            'Nivea',
            'Njoy',
            'No Fear',
            'Nocco',
            'Noebron',
            'Noppes Kringloop',
            'Nora',
            'NS',
            'Nussknacker',
            'Nutella',
            'Nutisal',
            'Nutricia',
            'Nuts',
            'Nxt',
            'NXT Beverwijk',
            'O2Life',
            'Oasis',
            'Oblomov',
            'Octagon',
            'Odorex',
            'Oishi',
            'Oke',
            'Okf',
            'Ola',
            'Old Jamaica',
            'Oldtimers',
            'Olvarit',
            'Olympic Hotel',
            'Optimel',
            'Oralb',
            'Orange',
            'Orangina',
            'Oreo',
            'Organics By Redbull',
            'Organix',
            'Oshee',
            'OTHER (For a Brand that is not in the picklist)',
            'Otrivin',
            'Pablo',
            'Pallmall',
            'Palm',
            'Palmolive',
            'Pampers',
            'Panadero',
            'Panter',
            'Papa Johns',
            'Parliament',
            'Partyballoons',
            'Passoa',
            'Paturain',
            'Paulaner',
            'Peachtree',
            'Pedigree',
            'Peijnenburg',
            'Pelican Rouge',
            'Pepsi',
            'Perla',
            'Perlenbacher',
            'Peroni',
            'Pfanner',
            'Piacetto',
            'Pickwick',
            'Picnic',
            'Piknik',
            'Pims',
            'Pinar',
            'Pine',
            'Piramide',
            'Pitt',
            'Pleinsud',
            'Plus',
            'Pokemon',
            'Pombar',
            'Poms',
            'Power',
            'Powerbooster',
            'Powerup',
            'Praxis',
            'Premium Dutch',
            'Prevalin',
            'Prince',
            'Pringles',
            'Profile',
            'Pucukharum',
            'Puff',
            'Pure Fruit',
            'Puregold',
            'PurePlus',
            'Puresoft',
            'Puschkin',
            'Pyke',
            'QNT Protein Shake',
            'Queens',
            'Quellbrunn',
            'Quemas',
            'Raak',
            'Rademakers',
            'Raffaello',
            'Rainbow Fizz',
            'Rajec',
            'Ramune',
            'RandM',
            'Rani',
            'Rayban',
            'Realtropical',
            'Red Bull',
            'Red Square',
            'Redband',
            'Reeses',
            'Reign',
            'Reissdorf Kolsch',
            'Remia',
            'Rexona',
            'Ribeaupierre',
            'Richmond',
            'Ricola',
            'Rioba',
            'Ritter Sport',
            'Rivella',
            'River',
            'Rizla',
            'Robinsons',
            'Rochefort',
            'Rocheval',
            'Rockstar',
            'Rodeo',
            'Romy',
            'Roosvicee',
            'Rothmans',
            'Royal Club',
            'Royal Dutch',
            'Ruba',
            'Rubicon',
            'Rumcola',
            'Rush',
            'Saguaro',
            'Saka',
            'Saklikoy',
            'Salento',
            'Salt',
            'San Benedetto',
            'San Celestino',
            'San Pellegrino',
            'Sanas',
            'Santa Emilia',
            'Sapporo',
            'Sappy',
            'Sarikiz',
            'Saskia',
            'Schultenbrau',
            'Schutters',
            'Schweppes',
            'Scotchman',
            'Segafredo',
            'Selpak',
            'Sensx',
            'Serra De Estrela',
            'Servero',
            'Shakeit',
            'Shakezz',
            'Shakhsar',
            'Shakura',
            'Sheba',
            'Shell',
            'Shiraz',
            'Sifres',
            'Siglitos',
            'Silifke',
            'Sinas',
            'Singha',
            'Sirma',
            'Sis',
            'Sisi',
            'Skittles',
            'Skyflakes',
            'Slammers',
            'Slimpie',
            'Sloanes',
            'Slurp',
            'Slurpie',
            'Smart',
            'Smarties',
            'Smint',
            'Smirnoff',
            'Smoeltjes',
            'Smok',
            'Smoking',
            'Smooth',
            'Smuldier',
            'Smullers',
            'Snack A Jacks',
            'Snelle Jelle',
            'Snickers',
            'Sol',
            'Solan',
            'Solevita',
            'SolMar',
            'Solo',
            'Solo Pro',
            'Somersby',
            'Sondey',
            'Sonnema',
            'Soplica',
            'Soulwater',
            'Sourcy',
            'Spa',
            'Spacepack',
            'Spam',
            'Span',
            'Spar',
            'Spargo',
            'Specialice',
            'Speedstar',
            'Split',
            'Sportlife',
            'Sportwater',
            'Sprite',
            'Stanley',
            'Starbucks',
            'Starsbar',
            'Statesman',
            'Stella Artois',
            'Stelz',
            'Stimorol',
            'Straffe Hendrik',
            'Strepsils',
            'Strike',
            'Stuyvesant',
            'Subway',
            'Sugarland',
            'Sultana',
            'Sun Lolly',
            'Supermalt',
            'Surango',
            'Tadim',
            'Taft',
            'Take Off',
            'Takis',
            'Taksi',
            'Tarczyn',
            'Tasting Good Vitamin Drink',
            'Tastino',
            'Tdk',
            'Teasers',
            'Tempo',
            'Tequila',
            'Texas',
            'Texels',
            'The Bulldog',
            'The Energy Drink',
            'Thuisbezorgd',
            'Tictac',
            'Tiger',
            'Tikkels',
            'Tikkie',
            'Tim Hortons',
            'Time Out',
            'Tinq',
            'Toblerone',
            'Toffifee',
            'Toffix',
            'Tonys',
            'Topdrop',
            'Topo',
            'Topo Chico',
            'Total',
            'Totem',
            'Trancetto',
            'Tribes',
            'Triplex',
            'Trocadero',
            'Trolli',
            'Troost',
            'Tropical',
            'Tropicana',
            'Troppie',
            'Tuborg',
            'Tuc',
            'Tutku',
            'Twix',
            'Two Chefs Brewing',
            'Two To One',
            'Tymbark',
            'Tysk',
            'Tyskie',
            'Uggo',
            'Ukcr',
            'Uludag',
            'Una',
            'Upbar',
            'Valvoline',
            'van A naar Beter',
            'Van Pur',
            'Vangils',
            'Vangilse',
            'Vanmelle',
            'Vannelle',
            'Varta',
            'Vega Libre',
            'Veltins',
            'Venco',
            'Veneto',
            'Vergers Gourmands',
            'Verkade',
            'Vezet',
            'Vidisic',
            'Vifit',
            'Viking',
            'Vimto',
            'Vio',
            'Viper',
            'Vishandel Plat',
            'Vitamin Well Awake',
            'Vitamin Well Defence',
            'Vitamin Well Focus',
            'Vitamin Well Hydrate',
            'Vitamin Well Refresh',
            'Vitamin Well Reload',
            'Vitamin Well Upgrade',
            'VitaminWell',
            'Viteau',
            'Vities',
            'Vittel',
            'Vlugge Japie',
            'Vluggertje',
            'Vogue',
            'Volt',
            'Volvic',
            'Vomar',
            'Vozol',
            'Vrieslollies',
            'Warheads',
            'Warka',
            'Warsteiner',
            'Wasa',
            'Weduwe Visser',
            'Werthers Original',
            'West',
            'Westminster',
            'Whiskas',
            'White Claw',
            'Wicky',
            'Wieckse',
            'Wild Bean Cafe',
            'Wilhelmina',
            'William Lawsons',
            'Winston',
            'Wisla',
            'Wybert',
            'Wyborowa',
            'Xbull',
            'Xixo',
            'Xoozz',
            'Xxx',
            'XXX Amsterdam Genetics',
            'Xylifresh',
            'Yakult',
            'Yogho Yogho',
            'Yoki',
            'Yono',
            'Yuoto',
            'Yutty',
            'Zaanse Hoeve',
            'Zatecky',
            'Zbyszko',
            'Zeeman',
            'Zewa',
            'Zonnatura',
            'Zotadkowa',
            'Zubr',
            'Zuivelhoeve',
            'Zwitsal',
            'Zywiec',
            'ZywiecZdroj',
        ];
    }
}
